points:
    zones:
        matrix:
            columns:
                0_5|0|0|0:
                    rows:
                        key1:
                            width: 1
                            height: 1
                            label: '3,0'
                            column_net: col_0
                            row_net: row_3
                        key2:
                            width: 1
                            height: 1
                            label: '2,0'
                            column_net: col_0
                            row_net: row_2
                        key3:
                            width: 1
                            height: 1
                            label: '1,0'
                            column_net: col_0
                            row_net: row_1
                        key4:
                            width: 1
                            height: 1
                            label: '0,0'
                            column_net: col_0
                            row_net: row_0
                    spread: 0.5 u
                    stagger: '-3.625 u'
                1_5|0|0|0:
                    rows:
                        key5:
                            width: 1
                            height: 1
                            label: '3,1'
                            column_net: col_1
                            row_net: row_3
                        key6:
                            width: 1
                            height: 1
                            label: '2,1'
                            column_net: col_1
                            row_net: row_2
                        key7:
                            width: 1
                            height: 1
                            label: '1,1'
                            column_net: col_1
                            row_net: row_1
                        key8:
                            width: 1
                            height: 1
                            label: '0,1'
                            column_net: col_1
                            row_net: row_0
                    stagger: 0.125 u
                2_5|0|0|0:
                    rows:
                        key9:
                            width: 1
                            height: 1
                            label: '3,2'
                            column_net: col_2
                            row_net: row_3
                        key10:
                            width: 1
                            height: 1
                            label: '2,2'
                            column_net: col_2
                            row_net: row_2
                        key11:
                            width: 1
                            height: 1
                            label: '1,2'
                            column_net: col_2
                            row_net: row_1
                        key12:
                            width: 1
                            height: 1
                            label: '0,2'
                            column_net: col_2
                            row_net: row_0
                    stagger: '-0.125 u'
                3_5|0|0|0:
                    rows:
                        key13:
                            width: 1
                            height: 1
                            label: '3,3'
                            column_net: col_3
                            row_net: row_3
                        key14:
                            width: 1
                            height: 1
                            label: '2,3'
                            column_net: col_3
                            row_net: row_2
                        key15:
                            width: 1
                            height: 1
                            label: '1,3'
                            column_net: col_3
                            row_net: row_1
                        key16:
                            width: 1
                            height: 1
                            label: '0,3'
                            column_net: col_3
                            row_net: row_0
                    stagger: 0.125 u
                4_5|0|0|0:
                    rows:
                        key17:
                            width: 1
                            height: 1
                            label: '3,4'
                            column_net: col_4
                            row_net: row_3
                        key18:
                            width: 1
                            height: 1
                            label: '2,4'
                            column_net: col_4
                            row_net: row_2
                        key19:
                            width: 1
                            height: 1
                            label: '1,4'
                            column_net: col_4
                            row_net: row_1
                        key20:
                            width: 1
                            height: 1
                            label: '0,4'
                            column_net: col_4
                            row_net: row_0
                    stagger: '-0.125 u'
                5_5|0|0|0:
                    rows:
                        key21:
                            width: 1
                            height: 1
                            label: '2,5'
                            column_net: col_5
                            row_net: row_2
                        key22:
                            width: 1
                            height: 1
                            label: '1,5'
                            column_net: col_5
                            row_net: row_1
                        key23:
                            width: 1
                            height: 1
                            label: '0,5'
                            column_net: col_5
                            row_net: row_0
                    stagger: 0.875 u
                5_625|-60|4_875|4_625:
                    rows:
                        key24:
                            width: 1.5
                            height: 1
                            label: '3,6'
                            column_net: col_6
                            row_net: row_3
                        key25:
                            width: 1.5
                            height: 1
                            label: '3,5'
                            column_net: col_5
                            row_net: row_3
                    spread: 0.125 u
                    stagger: '-3.375 u'
                    rotate: 60
                    origin:
                        - '-0.75 u'
                        - 1.5 u
                5_625|-60|4_875|4_625|dummy:
                    spread: 0 u
                    key:
                        skip: true
                    rotate: -60
                    origin:
                        - '-0.75 u'
                        - 1.5 u
                11_375|60|12_125|4_625:
                    rows:
                        key26:
                            width: 1.5
                            height: 1
                            label: '7,6'
                            column_net: col_6
                            row_net: row_7
                        key27:
                            width: 1.5
                            height: 1
                            label: '7,5'
                            column_net: col_5
                            row_net: row_7
                    spread: 5.75 u
                    stagger: 0 u
                    rotate: -60
                    origin:
                        - 0.75 u
                        - 1.5 u
                11_375|60|12_125|4_625|dummy:
                    spread: 0 u
                    key:
                        skip: true
                    rotate: 60
                    origin:
                        - 0.75 u
                        - 1.5 u
                11_5|0|0|0:
                    rows:
                        key28:
                            width: 1
                            height: 1
                            label: '6,5'
                            column_net: col_5
                            row_net: row_6
                        key29:
                            width: 1
                            height: 1
                            label: '5,5'
                            column_net: col_5
                            row_net: row_5
                        key30:
                            width: 1
                            height: 1
                            label: '4,5'
                            column_net: col_5
                            row_net: row_4
                    spread: 0.125 u
                    stagger: 3.375 u
                12_5|0|0|0:
                    rows:
                        key31:
                            width: 1
                            height: 1
                            label: '7,4'
                            column_net: col_4
                            row_net: row_7
                        key32:
                            width: 1
                            height: 1
                            label: '6,4'
                            column_net: col_4
                            row_net: row_6
                        key33:
                            width: 1
                            height: 1
                            label: '5,4'
                            column_net: col_4
                            row_net: row_5
                        key34:
                            width: 1
                            height: 1
                            label: '4,4'
                            column_net: col_4
                            row_net: row_4
                    stagger: '-0.875 u'
                13_5|0|0|0:
                    rows:
                        key35:
                            width: 1
                            height: 1
                            label: '7,3'
                            column_net: col_3
                            row_net: row_7
                        key36:
                            width: 1
                            height: 1
                            label: '6,3'
                            column_net: col_3
                            row_net: row_6
                        key37:
                            width: 1
                            height: 1
                            label: '5,3'
                            column_net: col_3
                            row_net: row_5
                        key38:
                            width: 1
                            height: 1
                            label: '4,3'
                            column_net: col_3
                            row_net: row_4
                    stagger: 0.125 u
                14_5|0|0|0:
                    rows:
                        key39:
                            width: 1
                            height: 1
                            label: '7,2'
                            column_net: col_2
                            row_net: row_7
                        key40:
                            width: 1
                            height: 1
                            label: '6,2'
                            column_net: col_2
                            row_net: row_6
                        key41:
                            width: 1
                            height: 1
                            label: '5,2'
                            column_net: col_2
                            row_net: row_5
                        key42:
                            width: 1
                            height: 1
                            label: '4,2'
                            column_net: col_2
                            row_net: row_4
                    stagger: '-0.125 u'
                15_5|0|0|0:
                    rows:
                        key43:
                            width: 1
                            height: 1
                            label: '7,1'
                            column_net: col_1
                            row_net: row_7
                        key44:
                            width: 1
                            height: 1
                            label: '6,1'
                            column_net: col_1
                            row_net: row_6
                        key45:
                            width: 1
                            height: 1
                            label: '5,1'
                            column_net: col_1
                            row_net: row_5
                        key46:
                            width: 1
                            height: 1
                            label: '4,1'
                            column_net: col_1
                            row_net: row_4
                    stagger: 0.125 u
                16_5|0|0|0:
                    rows:
                        key47:
                            width: 1
                            height: 1
                            label: '7,0'
                            column_net: col_0
                            row_net: row_7
                        key48:
                            width: 1
                            height: 1
                            label: '6,0'
                            column_net: col_0
                            row_net: row_6
                        key49:
                            width: 1
                            height: 1
                            label: '5,0'
                            column_net: col_0
                            row_net: row_5
                        key50:
                            width: 1
                            height: 1
                            label: '4,0'
                            column_net: col_0
                            row_net: row_4
                    stagger: '-0.125 u'
            key:
                footprints:
                    switch:
                        type: mx
                        nets:
                            to: '=colrow'
                            from: '=row_net'
                        params:
                            hotswap: true
                            reverse: true
                    diode:
                        type: diode
                        anchor:
                            rotate: 180
                            shift:
                                - 0
                                - -5
                        nets:
                            from: '=colrow'
                            to: '=column_net'
pcbs:
    main:
        outlines:
            plate:
                outline: pcb
                layer: Edge.Cuts
        footprints:
            mcu:
                type: promicro_rev_routed
                anchor:
                    rotate: 270
                    shift:
                        - 6.75 U
                        - '-1.5 U'
                nets:
                    P20: col_0
                    P19: col_1
                    P18: col_2
                    P15: col_3
                    P14: col_4
                    P16: col_5
                    P10: col_6
                    P2: row_0
                    P3: row_1
                    P4: row_2
                    P5: row_3
            trrs:
                type: trrs_rev
                anchor:
                    rotate: 270
                    shift:
                        - 7.25 U
                        - '-3 U'
                nets:
                    A: P1
                    B: GND
                    C: P0
                    D: VCC
